### ISSUE TITLE
Low-rank approximation of the differential Lyapunov/Riccati equations

### ISSUE THREAD

**Issue by loiseaujc** [nekStab/LightROM#3]

**Comment by Simkern** [comment]
The first version of the DLRA for the Lyapunov equation is now ready. I created an example for the 2D laplacian. Do you want to review it now or wait until it works also for the Riccatti equation?

N.B.: For now I haven't adapted the code to the LTI types.

**Comment by loiseaujc** [comment]
The `lti` types are just some lines of code I quickly scribbled to have something to include in the first commit.
We still need to think about how to encapsulate the knowledge of the system into a single fortran object (or not).

**Comment by Simkern** [comment]
Completed with recent push to dev
